### ISSUE TITLE
Module instead of an addon?

### ISSUE THREAD

**Issue by nathanfranke** [fenix-hub/godot-engine.godot-stories#1]
This would mean basically rewriting everything in C++ but I don't see why this is a project-specific addon rather than a module.

**Comment by fenix-hub** [comment]
Hi @nathanfranke ! What's the reason why you think this should be made into a module?
This would require people to compile it in the engine just to get this little funny feature, and I don't think that this would be accepted as a standard module in the godot engine.
Keeping it as an addon would make it easier to use. But I'm curious, so let's talk about that

**Comment by nathanfranke** [comment]
Right now you would have to install this to the project which doesn't make sense, particularly when it comes to version control. In this case you need to impose it's usage for everyone else working on the project.

**Comment by WolfgangSenff** [comment]
I might be misunderstanding, but no, no reason for this to be a module. At the moment, it works very well with version control. Add-ons are a normal thing you have to deal with.

**Comment by WolfgangSenff** [comment]
Removing this comment because I did not realize this was not the main repository for the Firebase plugin. :D My bad!

**Comment by fenix-hub** [comment]
> Right now you would have to install this to the project which doesn't make sense, particularly when it comes to version control. In this case you need to impose it's usage for everyone else working on the project.

What do you mean by that? Maybe I'm not understading the problem.
That's how addons work on Godot: you can "install" it in your project from github or the asset lib and then use it in that project. If you upload your project in a repository, including the addons folder, you will also have the plugin for anyone who will clone/pull your repo.
I get that if you want to have the same plugin on another project you will have to download it again, but that's how Godot works for every plugin.
Making it a module would for sure allow you to always have it in each project you create, but it would only work if you:
1) compile the engine every single time there is an update adding this module
2) download and subsistute the module if it needs to be updated

Which to me seems a lot of work to get just an Twitter API scraper, but maybe I'm missing the point

**Comment by nathanfranke** [comment]
I completely understand that, I think for now it's fine, maybe this would go better as a feature request for Godot so that you can install "editor add-ons" that are on every project and don't show up on version control
